// Code generated by protoc-gen-go.
// source: zebra.proto
// DO NOT EDIT!

/*
Package zebra is a generated protocol buffer package.

It is generated from these files:
	zebra.proto

It has these top-level messages:
	InterfaceRequest
	InterfaceUpdate
	RouterIdRequest
	RouterIdUpdate
	RedistributeIPv4Request
	RedistributeIPv6Request
	Prefix
	Nexthop
	Address
	RouteIPv4
	RouteIPv6
*/
package zebra

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RouteType int32

const (
	RouteType_RIB_UNKNOWN   RouteType = 0
	RouteType_RIB_KERNEL    RouteType = 1
	RouteType_RIB_CONNECTED RouteType = 2
	RouteType_RIB_STATIC    RouteType = 3
	RouteType_RIB_RIP       RouteType = 4
	RouteType_RIB_OSPF      RouteType = 5
	RouteType_RIB_ISIS      RouteType = 6
	RouteType_RIB_BGP       RouteType = 7
)

var RouteType_name = map[int32]string{
	0: "RIB_UNKNOWN",
	1: "RIB_KERNEL",
	2: "RIB_CONNECTED",
	3: "RIB_STATIC",
	4: "RIB_RIP",
	5: "RIB_OSPF",
	6: "RIB_ISIS",
	7: "RIB_BGP",
}
var RouteType_value = map[string]int32{
	"RIB_UNKNOWN":   0,
	"RIB_KERNEL":    1,
	"RIB_CONNECTED": 2,
	"RIB_STATIC":    3,
	"RIB_RIP":       4,
	"RIB_OSPF":      5,
	"RIB_ISIS":      6,
	"RIB_BGP":       7,
}

func (x RouteType) String() string {
	return proto.EnumName(RouteType_name, int32(x))
}
func (RouteType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RouteSubType int32

const (
	RouteSubType_RIB_SUB_OSPF_IA         RouteSubType = 0
	RouteSubType_RIB_SUB_OSPF_NSSA_1     RouteSubType = 1
	RouteSubType_RIB_SUB_OSPF_NSSA_2     RouteSubType = 2
	RouteSubType_RIB_SUB_OSPF_EXTERNAL_1 RouteSubType = 3
	RouteSubType_RIB_SUB_OSPF_EXTERNAL_2 RouteSubType = 4
	RouteSubType_RIB_SUB_BGP_IBGP        RouteSubType = 5
	RouteSubType_RIB_SUB_BGP_EBGP        RouteSubType = 6
	RouteSubType_RIB_SUB_BGP_CONFED      RouteSubType = 7
	RouteSubType_RIB_SUB_ISIS_L1         RouteSubType = 8
	RouteSubType_RIB_SUB_ISIS_L2         RouteSubType = 9
	RouteSubType_RIB_SUB_ISIS_IA         RouteSubType = 10
)

var RouteSubType_name = map[int32]string{
	0:  "RIB_SUB_OSPF_IA",
	1:  "RIB_SUB_OSPF_NSSA_1",
	2:  "RIB_SUB_OSPF_NSSA_2",
	3:  "RIB_SUB_OSPF_EXTERNAL_1",
	4:  "RIB_SUB_OSPF_EXTERNAL_2",
	5:  "RIB_SUB_BGP_IBGP",
	6:  "RIB_SUB_BGP_EBGP",
	7:  "RIB_SUB_BGP_CONFED",
	8:  "RIB_SUB_ISIS_L1",
	9:  "RIB_SUB_ISIS_L2",
	10: "RIB_SUB_ISIS_IA",
}
var RouteSubType_value = map[string]int32{
	"RIB_SUB_OSPF_IA":         0,
	"RIB_SUB_OSPF_NSSA_1":     1,
	"RIB_SUB_OSPF_NSSA_2":     2,
	"RIB_SUB_OSPF_EXTERNAL_1": 3,
	"RIB_SUB_OSPF_EXTERNAL_2": 4,
	"RIB_SUB_BGP_IBGP":        5,
	"RIB_SUB_BGP_EBGP":        6,
	"RIB_SUB_BGP_CONFED":      7,
	"RIB_SUB_ISIS_L1":         8,
	"RIB_SUB_ISIS_L2":         9,
	"RIB_SUB_ISIS_IA":         10,
}

func (x RouteSubType) String() string {
	return proto.EnumName(RouteSubType_name, int32(x))
}
func (RouteSubType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Op int32

const (
	Op_NoOperation              Op = 0
	Op_InterfaceSubscribe       Op = 1
	Op_InterfaceUnsubscribe     Op = 2
	Op_RouterIdSubscribe        Op = 3
	Op_RouterIdUnsubscribe      Op = 4
	Op_RedistSubscribe          Op = 5
	Op_RedistUnsubscribe        Op = 6
	Op_RedistDefaultSubscribe   Op = 7
	Op_RedistDefaultUnsubscribe Op = 8
	Op_RouteAdd                 Op = 9
	Op_RouteDelete              Op = 10
	Op_InterfaceAdd             Op = 11
	Op_InterfaceDelete          Op = 12
	Op_InterfaceAddrAdd         Op = 13
	Op_InterfaceAddrDelete      Op = 14
	Op_InterfaceUp              Op = 15
	Op_InterfaceDown            Op = 16
	Op_InterfaceFlagChange      Op = 17
	Op_InterfaceNameChange      Op = 18
	Op_InterfaceMtuChange       Op = 19
)

var Op_name = map[int32]string{
	0:  "NoOperation",
	1:  "InterfaceSubscribe",
	2:  "InterfaceUnsubscribe",
	3:  "RouterIdSubscribe",
	4:  "RouterIdUnsubscribe",
	5:  "RedistSubscribe",
	6:  "RedistUnsubscribe",
	7:  "RedistDefaultSubscribe",
	8:  "RedistDefaultUnsubscribe",
	9:  "RouteAdd",
	10: "RouteDelete",
	11: "InterfaceAdd",
	12: "InterfaceDelete",
	13: "InterfaceAddrAdd",
	14: "InterfaceAddrDelete",
	15: "InterfaceUp",
	16: "InterfaceDown",
	17: "InterfaceFlagChange",
	18: "InterfaceNameChange",
	19: "InterfaceMtuChange",
}
var Op_value = map[string]int32{
	"NoOperation":              0,
	"InterfaceSubscribe":       1,
	"InterfaceUnsubscribe":     2,
	"RouterIdSubscribe":        3,
	"RouterIdUnsubscribe":      4,
	"RedistSubscribe":          5,
	"RedistUnsubscribe":        6,
	"RedistDefaultSubscribe":   7,
	"RedistDefaultUnsubscribe": 8,
	"RouteAdd":                 9,
	"RouteDelete":              10,
	"InterfaceAdd":             11,
	"InterfaceDelete":          12,
	"InterfaceAddrAdd":         13,
	"InterfaceAddrDelete":      14,
	"InterfaceUp":              15,
	"InterfaceDown":            16,
	"InterfaceFlagChange":      17,
	"InterfaceNameChange":      18,
	"InterfaceMtuChange":       19,
}

func (x Op) String() string {
	return proto.EnumName(Op_name, int32(x))
}
func (Op) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type InterfaceRequest struct {
	Op    Op     `protobuf:"varint,1,opt,name=op,enum=zebra.Op" json:"op,omitempty"`
	VrfId uint32 `protobuf:"varint,2,opt,name=vrf_id,json=vrfId" json:"vrf_id,omitempty"`
}

func (m *InterfaceRequest) Reset()                    { *m = InterfaceRequest{} }
func (m *InterfaceRequest) String() string            { return proto.CompactTextString(m) }
func (*InterfaceRequest) ProtoMessage()               {}
func (*InterfaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InterfaceRequest) GetOp() Op {
	if m != nil {
		return m.Op
	}
	return Op_NoOperation
}

func (m *InterfaceRequest) GetVrfId() uint32 {
	if m != nil {
		return m.VrfId
	}
	return 0
}

type InterfaceUpdate struct {
	Op       Op         `protobuf:"varint,1,opt,name=op,enum=zebra.Op" json:"op,omitempty"`
	VrfId    uint32     `protobuf:"varint,2,opt,name=vrf_id,json=vrfId" json:"vrf_id,omitempty"`
	Name     string     `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Index    uint32     `protobuf:"varint,4,opt,name=index" json:"index,omitempty"`
	Mtu      uint32     `protobuf:"varint,5,opt,name=mtu" json:"mtu,omitempty"`
	Metric   uint32     `protobuf:"varint,6,opt,name=metric" json:"metric,omitempty"`
	AddrIpv4 []*Address `protobuf:"bytes,7,rep,name=addr_ipv4,json=addrIpv4" json:"addr_ipv4,omitempty"`
	AddrIpv6 []*Address `protobuf:"bytes,8,rep,name=addr_ipv6,json=addrIpv6" json:"addr_ipv6,omitempty"`
}

func (m *InterfaceUpdate) Reset()                    { *m = InterfaceUpdate{} }
func (m *InterfaceUpdate) String() string            { return proto.CompactTextString(m) }
func (*InterfaceUpdate) ProtoMessage()               {}
func (*InterfaceUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InterfaceUpdate) GetOp() Op {
	if m != nil {
		return m.Op
	}
	return Op_NoOperation
}

func (m *InterfaceUpdate) GetVrfId() uint32 {
	if m != nil {
		return m.VrfId
	}
	return 0
}

func (m *InterfaceUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InterfaceUpdate) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *InterfaceUpdate) GetMtu() uint32 {
	if m != nil {
		return m.Mtu
	}
	return 0
}

func (m *InterfaceUpdate) GetMetric() uint32 {
	if m != nil {
		return m.Metric
	}
	return 0
}

func (m *InterfaceUpdate) GetAddrIpv4() []*Address {
	if m != nil {
		return m.AddrIpv4
	}
	return nil
}

func (m *InterfaceUpdate) GetAddrIpv6() []*Address {
	if m != nil {
		return m.AddrIpv6
	}
	return nil
}

type RouterIdRequest struct {
	Op    Op     `protobuf:"varint,1,opt,name=op,enum=zebra.Op" json:"op,omitempty"`
	VrfId uint32 `protobuf:"varint,2,opt,name=vrf_id,json=vrfId" json:"vrf_id,omitempty"`
}

func (m *RouterIdRequest) Reset()                    { *m = RouterIdRequest{} }
func (m *RouterIdRequest) String() string            { return proto.CompactTextString(m) }
func (*RouterIdRequest) ProtoMessage()               {}
func (*RouterIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RouterIdRequest) GetOp() Op {
	if m != nil {
		return m.Op
	}
	return Op_NoOperation
}

func (m *RouterIdRequest) GetVrfId() uint32 {
	if m != nil {
		return m.VrfId
	}
	return 0
}

type RouterIdUpdate struct {
	VrfId    uint32 `protobuf:"varint,1,opt,name=vrf_id,json=vrfId" json:"vrf_id,omitempty"`
	RouterId []byte `protobuf:"bytes,2,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
}

func (m *RouterIdUpdate) Reset()                    { *m = RouterIdUpdate{} }
func (m *RouterIdUpdate) String() string            { return proto.CompactTextString(m) }
func (*RouterIdUpdate) ProtoMessage()               {}
func (*RouterIdUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RouterIdUpdate) GetVrfId() uint32 {
	if m != nil {
		return m.VrfId
	}
	return 0
}

func (m *RouterIdUpdate) GetRouterId() []byte {
	if m != nil {
		return m.RouterId
	}
	return nil
}

type RedistributeIPv4Request struct {
	Op        Op        `protobuf:"varint,1,opt,name=op,enum=zebra.Op" json:"op,omitempty"`
	VrfId     uint32    `protobuf:"varint,2,opt,name=vrf_id,json=vrfId" json:"vrf_id,omitempty"`
	RouteType RouteType `protobuf:"varint,4,opt,name=route_type,json=routeType,enum=zebra.RouteType" json:"route_type,omitempty"`
}

func (m *RedistributeIPv4Request) Reset()                    { *m = RedistributeIPv4Request{} }
func (m *RedistributeIPv4Request) String() string            { return proto.CompactTextString(m) }
func (*RedistributeIPv4Request) ProtoMessage()               {}
func (*RedistributeIPv4Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RedistributeIPv4Request) GetOp() Op {
	if m != nil {
		return m.Op
	}
	return Op_NoOperation
}

func (m *RedistributeIPv4Request) GetVrfId() uint32 {
	if m != nil {
		return m.VrfId
	}
	return 0
}

func (m *RedistributeIPv4Request) GetRouteType() RouteType {
	if m != nil {
		return m.RouteType
	}
	return RouteType_RIB_UNKNOWN
}

type RedistributeIPv6Request struct {
	Op        Op        `protobuf:"varint,1,opt,name=op,enum=zebra.Op" json:"op,omitempty"`
	VrfId     uint32    `protobuf:"varint,2,opt,name=vrf_id,json=vrfId" json:"vrf_id,omitempty"`
	RouteType RouteType `protobuf:"varint,4,opt,name=route_type,json=routeType,enum=zebra.RouteType" json:"route_type,omitempty"`
}

func (m *RedistributeIPv6Request) Reset()                    { *m = RedistributeIPv6Request{} }
func (m *RedistributeIPv6Request) String() string            { return proto.CompactTextString(m) }
func (*RedistributeIPv6Request) ProtoMessage()               {}
func (*RedistributeIPv6Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RedistributeIPv6Request) GetOp() Op {
	if m != nil {
		return m.Op
	}
	return Op_NoOperation
}

func (m *RedistributeIPv6Request) GetVrfId() uint32 {
	if m != nil {
		return m.VrfId
	}
	return 0
}

func (m *RedistributeIPv6Request) GetRouteType() RouteType {
	if m != nil {
		return m.RouteType
	}
	return RouteType_RIB_UNKNOWN
}

type Prefix struct {
	Addr   []byte `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Length uint32 `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
}

func (m *Prefix) Reset()                    { *m = Prefix{} }
func (m *Prefix) String() string            { return proto.CompactTextString(m) }
func (*Prefix) ProtoMessage()               {}
func (*Prefix) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Prefix) GetAddr() []byte {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *Prefix) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

type Nexthop struct {
	Addr    []byte `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Ifindex uint32 `protobuf:"varint,2,opt,name=ifindex" json:"ifindex,omitempty"`
}

func (m *Nexthop) Reset()                    { *m = Nexthop{} }
func (m *Nexthop) String() string            { return proto.CompactTextString(m) }
func (*Nexthop) ProtoMessage()               {}
func (*Nexthop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Nexthop) GetAddr() []byte {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *Nexthop) GetIfindex() uint32 {
	if m != nil {
		return m.Ifindex
	}
	return 0
}

type Address struct {
	Addr  *Prefix `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Flags uint32  `protobuf:"varint,2,opt,name=flags" json:"flags,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Address) GetAddr() *Prefix {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *Address) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

type RouteIPv4 struct {
	Op       Op           `protobuf:"varint,1,opt,name=op,enum=zebra.Op" json:"op,omitempty"`
	VrfId    uint32       `protobuf:"varint,2,opt,name=vrf_id,json=vrfId" json:"vrf_id,omitempty"`
	Type     RouteType    `protobuf:"varint,3,opt,name=type,enum=zebra.RouteType" json:"type,omitempty"`
	SubType  RouteSubType `protobuf:"varint,4,opt,name=sub_type,json=subType,enum=zebra.RouteSubType" json:"sub_type,omitempty"`
	Prefix   *Prefix      `protobuf:"bytes,5,opt,name=prefix" json:"prefix,omitempty"`
	Distance uint32       `protobuf:"varint,6,opt,name=distance" json:"distance,omitempty"`
	Metric   uint32       `protobuf:"varint,7,opt,name=metric" json:"metric,omitempty"`
	Tag      uint32       `protobuf:"varint,8,opt,name=tag" json:"tag,omitempty"`
	Color    []string     `protobuf:"bytes,9,rep,name=color" json:"color,omitempty"`
	Nexthops []*Nexthop   `protobuf:"bytes,10,rep,name=nexthops" json:"nexthops,omitempty"`
}

func (m *RouteIPv4) Reset()                    { *m = RouteIPv4{} }
func (m *RouteIPv4) String() string            { return proto.CompactTextString(m) }
func (*RouteIPv4) ProtoMessage()               {}
func (*RouteIPv4) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RouteIPv4) GetOp() Op {
	if m != nil {
		return m.Op
	}
	return Op_NoOperation
}

func (m *RouteIPv4) GetVrfId() uint32 {
	if m != nil {
		return m.VrfId
	}
	return 0
}

func (m *RouteIPv4) GetType() RouteType {
	if m != nil {
		return m.Type
	}
	return RouteType_RIB_UNKNOWN
}

func (m *RouteIPv4) GetSubType() RouteSubType {
	if m != nil {
		return m.SubType
	}
	return RouteSubType_RIB_SUB_OSPF_IA
}

func (m *RouteIPv4) GetPrefix() *Prefix {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *RouteIPv4) GetDistance() uint32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *RouteIPv4) GetMetric() uint32 {
	if m != nil {
		return m.Metric
	}
	return 0
}

func (m *RouteIPv4) GetTag() uint32 {
	if m != nil {
		return m.Tag
	}
	return 0
}

func (m *RouteIPv4) GetColor() []string {
	if m != nil {
		return m.Color
	}
	return nil
}

func (m *RouteIPv4) GetNexthops() []*Nexthop {
	if m != nil {
		return m.Nexthops
	}
	return nil
}

type RouteIPv6 struct {
	Op       Op           `protobuf:"varint,1,opt,name=op,enum=zebra.Op" json:"op,omitempty"`
	VrfId    uint32       `protobuf:"varint,2,opt,name=vrf_id,json=vrfId" json:"vrf_id,omitempty"`
	Type     RouteType    `protobuf:"varint,3,opt,name=type,enum=zebra.RouteType" json:"type,omitempty"`
	SubType  RouteSubType `protobuf:"varint,4,opt,name=sub_type,json=subType,enum=zebra.RouteSubType" json:"sub_type,omitempty"`
	Prefix   *Prefix      `protobuf:"bytes,5,opt,name=prefix" json:"prefix,omitempty"`
	Distance uint32       `protobuf:"varint,6,opt,name=distance" json:"distance,omitempty"`
	Metric   uint32       `protobuf:"varint,7,opt,name=metric" json:"metric,omitempty"`
	Tag      uint32       `protobuf:"varint,8,opt,name=tag" json:"tag,omitempty"`
	Color    []string     `protobuf:"bytes,9,rep,name=color" json:"color,omitempty"`
	Nexthops []*Nexthop   `protobuf:"bytes,10,rep,name=nexthops" json:"nexthops,omitempty"`
}

func (m *RouteIPv6) Reset()                    { *m = RouteIPv6{} }
func (m *RouteIPv6) String() string            { return proto.CompactTextString(m) }
func (*RouteIPv6) ProtoMessage()               {}
func (*RouteIPv6) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *RouteIPv6) GetOp() Op {
	if m != nil {
		return m.Op
	}
	return Op_NoOperation
}

func (m *RouteIPv6) GetVrfId() uint32 {
	if m != nil {
		return m.VrfId
	}
	return 0
}

func (m *RouteIPv6) GetType() RouteType {
	if m != nil {
		return m.Type
	}
	return RouteType_RIB_UNKNOWN
}

func (m *RouteIPv6) GetSubType() RouteSubType {
	if m != nil {
		return m.SubType
	}
	return RouteSubType_RIB_SUB_OSPF_IA
}

func (m *RouteIPv6) GetPrefix() *Prefix {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *RouteIPv6) GetDistance() uint32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *RouteIPv6) GetMetric() uint32 {
	if m != nil {
		return m.Metric
	}
	return 0
}

func (m *RouteIPv6) GetTag() uint32 {
	if m != nil {
		return m.Tag
	}
	return 0
}

func (m *RouteIPv6) GetColor() []string {
	if m != nil {
		return m.Color
	}
	return nil
}

func (m *RouteIPv6) GetNexthops() []*Nexthop {
	if m != nil {
		return m.Nexthops
	}
	return nil
}

func init() {
	proto.RegisterType((*InterfaceRequest)(nil), "zebra.InterfaceRequest")
	proto.RegisterType((*InterfaceUpdate)(nil), "zebra.InterfaceUpdate")
	proto.RegisterType((*RouterIdRequest)(nil), "zebra.RouterIdRequest")
	proto.RegisterType((*RouterIdUpdate)(nil), "zebra.RouterIdUpdate")
	proto.RegisterType((*RedistributeIPv4Request)(nil), "zebra.RedistributeIPv4Request")
	proto.RegisterType((*RedistributeIPv6Request)(nil), "zebra.RedistributeIPv6Request")
	proto.RegisterType((*Prefix)(nil), "zebra.Prefix")
	proto.RegisterType((*Nexthop)(nil), "zebra.Nexthop")
	proto.RegisterType((*Address)(nil), "zebra.Address")
	proto.RegisterType((*RouteIPv4)(nil), "zebra.RouteIPv4")
	proto.RegisterType((*RouteIPv6)(nil), "zebra.RouteIPv6")
	proto.RegisterEnum("zebra.RouteType", RouteType_name, RouteType_value)
	proto.RegisterEnum("zebra.RouteSubType", RouteSubType_name, RouteSubType_value)
	proto.RegisterEnum("zebra.Op", Op_name, Op_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Zebra service

type ZebraClient interface {
	InterfaceService(ctx context.Context, opts ...grpc.CallOption) (Zebra_InterfaceServiceClient, error)
	RouterIdService(ctx context.Context, opts ...grpc.CallOption) (Zebra_RouterIdServiceClient, error)
	RedistributeIPv4Service(ctx context.Context, opts ...grpc.CallOption) (Zebra_RedistributeIPv4ServiceClient, error)
	RedistributeIPv6Service(ctx context.Context, opts ...grpc.CallOption) (Zebra_RedistributeIPv6ServiceClient, error)
	RouteIPv4Service(ctx context.Context, opts ...grpc.CallOption) (Zebra_RouteIPv4ServiceClient, error)
	RouteIPv6Service(ctx context.Context, opts ...grpc.CallOption) (Zebra_RouteIPv6ServiceClient, error)
}

type zebraClient struct {
	cc *grpc.ClientConn
}

func NewZebraClient(cc *grpc.ClientConn) ZebraClient {
	return &zebraClient{cc}
}

func (c *zebraClient) InterfaceService(ctx context.Context, opts ...grpc.CallOption) (Zebra_InterfaceServiceClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Zebra_serviceDesc.Streams[0], c.cc, "/zebra.Zebra/InterfaceService", opts...)
	if err != nil {
		return nil, err
	}
	x := &zebraInterfaceServiceClient{stream}
	return x, nil
}

type Zebra_InterfaceServiceClient interface {
	Send(*InterfaceRequest) error
	Recv() (*InterfaceUpdate, error)
	grpc.ClientStream
}

type zebraInterfaceServiceClient struct {
	grpc.ClientStream
}

func (x *zebraInterfaceServiceClient) Send(m *InterfaceRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *zebraInterfaceServiceClient) Recv() (*InterfaceUpdate, error) {
	m := new(InterfaceUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *zebraClient) RouterIdService(ctx context.Context, opts ...grpc.CallOption) (Zebra_RouterIdServiceClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Zebra_serviceDesc.Streams[1], c.cc, "/zebra.Zebra/RouterIdService", opts...)
	if err != nil {
		return nil, err
	}
	x := &zebraRouterIdServiceClient{stream}
	return x, nil
}

type Zebra_RouterIdServiceClient interface {
	Send(*RouterIdRequest) error
	Recv() (*RouterIdUpdate, error)
	grpc.ClientStream
}

type zebraRouterIdServiceClient struct {
	grpc.ClientStream
}

func (x *zebraRouterIdServiceClient) Send(m *RouterIdRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *zebraRouterIdServiceClient) Recv() (*RouterIdUpdate, error) {
	m := new(RouterIdUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *zebraClient) RedistributeIPv4Service(ctx context.Context, opts ...grpc.CallOption) (Zebra_RedistributeIPv4ServiceClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Zebra_serviceDesc.Streams[2], c.cc, "/zebra.Zebra/RedistributeIPv4Service", opts...)
	if err != nil {
		return nil, err
	}
	x := &zebraRedistributeIPv4ServiceClient{stream}
	return x, nil
}

type Zebra_RedistributeIPv4ServiceClient interface {
	Send(*RedistributeIPv4Request) error
	Recv() (*RouteIPv4, error)
	grpc.ClientStream
}

type zebraRedistributeIPv4ServiceClient struct {
	grpc.ClientStream
}

func (x *zebraRedistributeIPv4ServiceClient) Send(m *RedistributeIPv4Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *zebraRedistributeIPv4ServiceClient) Recv() (*RouteIPv4, error) {
	m := new(RouteIPv4)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *zebraClient) RedistributeIPv6Service(ctx context.Context, opts ...grpc.CallOption) (Zebra_RedistributeIPv6ServiceClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Zebra_serviceDesc.Streams[3], c.cc, "/zebra.Zebra/RedistributeIPv6Service", opts...)
	if err != nil {
		return nil, err
	}
	x := &zebraRedistributeIPv6ServiceClient{stream}
	return x, nil
}

type Zebra_RedistributeIPv6ServiceClient interface {
	Send(*RedistributeIPv6Request) error
	Recv() (*RouteIPv6, error)
	grpc.ClientStream
}

type zebraRedistributeIPv6ServiceClient struct {
	grpc.ClientStream
}

func (x *zebraRedistributeIPv6ServiceClient) Send(m *RedistributeIPv6Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *zebraRedistributeIPv6ServiceClient) Recv() (*RouteIPv6, error) {
	m := new(RouteIPv6)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *zebraClient) RouteIPv4Service(ctx context.Context, opts ...grpc.CallOption) (Zebra_RouteIPv4ServiceClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Zebra_serviceDesc.Streams[4], c.cc, "/zebra.Zebra/RouteIPv4Service", opts...)
	if err != nil {
		return nil, err
	}
	x := &zebraRouteIPv4ServiceClient{stream}
	return x, nil
}

type Zebra_RouteIPv4ServiceClient interface {
	Send(*RouteIPv4) error
	Recv() (*RouteIPv4, error)
	grpc.ClientStream
}

type zebraRouteIPv4ServiceClient struct {
	grpc.ClientStream
}

func (x *zebraRouteIPv4ServiceClient) Send(m *RouteIPv4) error {
	return x.ClientStream.SendMsg(m)
}

func (x *zebraRouteIPv4ServiceClient) Recv() (*RouteIPv4, error) {
	m := new(RouteIPv4)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *zebraClient) RouteIPv6Service(ctx context.Context, opts ...grpc.CallOption) (Zebra_RouteIPv6ServiceClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Zebra_serviceDesc.Streams[5], c.cc, "/zebra.Zebra/RouteIPv6Service", opts...)
	if err != nil {
		return nil, err
	}
	x := &zebraRouteIPv6ServiceClient{stream}
	return x, nil
}

type Zebra_RouteIPv6ServiceClient interface {
	Send(*RouteIPv6) error
	Recv() (*RouteIPv6, error)
	grpc.ClientStream
}

type zebraRouteIPv6ServiceClient struct {
	grpc.ClientStream
}

func (x *zebraRouteIPv6ServiceClient) Send(m *RouteIPv6) error {
	return x.ClientStream.SendMsg(m)
}

func (x *zebraRouteIPv6ServiceClient) Recv() (*RouteIPv6, error) {
	m := new(RouteIPv6)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Zebra service

type ZebraServer interface {
	InterfaceService(Zebra_InterfaceServiceServer) error
	RouterIdService(Zebra_RouterIdServiceServer) error
	RedistributeIPv4Service(Zebra_RedistributeIPv4ServiceServer) error
	RedistributeIPv6Service(Zebra_RedistributeIPv6ServiceServer) error
	RouteIPv4Service(Zebra_RouteIPv4ServiceServer) error
	RouteIPv6Service(Zebra_RouteIPv6ServiceServer) error
}

func RegisterZebraServer(s *grpc.Server, srv ZebraServer) {
	s.RegisterService(&_Zebra_serviceDesc, srv)
}

func _Zebra_InterfaceService_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ZebraServer).InterfaceService(&zebraInterfaceServiceServer{stream})
}

type Zebra_InterfaceServiceServer interface {
	Send(*InterfaceUpdate) error
	Recv() (*InterfaceRequest, error)
	grpc.ServerStream
}

type zebraInterfaceServiceServer struct {
	grpc.ServerStream
}

func (x *zebraInterfaceServiceServer) Send(m *InterfaceUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func (x *zebraInterfaceServiceServer) Recv() (*InterfaceRequest, error) {
	m := new(InterfaceRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Zebra_RouterIdService_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ZebraServer).RouterIdService(&zebraRouterIdServiceServer{stream})
}

type Zebra_RouterIdServiceServer interface {
	Send(*RouterIdUpdate) error
	Recv() (*RouterIdRequest, error)
	grpc.ServerStream
}

type zebraRouterIdServiceServer struct {
	grpc.ServerStream
}

func (x *zebraRouterIdServiceServer) Send(m *RouterIdUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func (x *zebraRouterIdServiceServer) Recv() (*RouterIdRequest, error) {
	m := new(RouterIdRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Zebra_RedistributeIPv4Service_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ZebraServer).RedistributeIPv4Service(&zebraRedistributeIPv4ServiceServer{stream})
}

type Zebra_RedistributeIPv4ServiceServer interface {
	Send(*RouteIPv4) error
	Recv() (*RedistributeIPv4Request, error)
	grpc.ServerStream
}

type zebraRedistributeIPv4ServiceServer struct {
	grpc.ServerStream
}

func (x *zebraRedistributeIPv4ServiceServer) Send(m *RouteIPv4) error {
	return x.ServerStream.SendMsg(m)
}

func (x *zebraRedistributeIPv4ServiceServer) Recv() (*RedistributeIPv4Request, error) {
	m := new(RedistributeIPv4Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Zebra_RedistributeIPv6Service_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ZebraServer).RedistributeIPv6Service(&zebraRedistributeIPv6ServiceServer{stream})
}

type Zebra_RedistributeIPv6ServiceServer interface {
	Send(*RouteIPv6) error
	Recv() (*RedistributeIPv6Request, error)
	grpc.ServerStream
}

type zebraRedistributeIPv6ServiceServer struct {
	grpc.ServerStream
}

func (x *zebraRedistributeIPv6ServiceServer) Send(m *RouteIPv6) error {
	return x.ServerStream.SendMsg(m)
}

func (x *zebraRedistributeIPv6ServiceServer) Recv() (*RedistributeIPv6Request, error) {
	m := new(RedistributeIPv6Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Zebra_RouteIPv4Service_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ZebraServer).RouteIPv4Service(&zebraRouteIPv4ServiceServer{stream})
}

type Zebra_RouteIPv4ServiceServer interface {
	Send(*RouteIPv4) error
	Recv() (*RouteIPv4, error)
	grpc.ServerStream
}

type zebraRouteIPv4ServiceServer struct {
	grpc.ServerStream
}

func (x *zebraRouteIPv4ServiceServer) Send(m *RouteIPv4) error {
	return x.ServerStream.SendMsg(m)
}

func (x *zebraRouteIPv4ServiceServer) Recv() (*RouteIPv4, error) {
	m := new(RouteIPv4)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Zebra_RouteIPv6Service_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ZebraServer).RouteIPv6Service(&zebraRouteIPv6ServiceServer{stream})
}

type Zebra_RouteIPv6ServiceServer interface {
	Send(*RouteIPv6) error
	Recv() (*RouteIPv6, error)
	grpc.ServerStream
}

type zebraRouteIPv6ServiceServer struct {
	grpc.ServerStream
}

func (x *zebraRouteIPv6ServiceServer) Send(m *RouteIPv6) error {
	return x.ServerStream.SendMsg(m)
}

func (x *zebraRouteIPv6ServiceServer) Recv() (*RouteIPv6, error) {
	m := new(RouteIPv6)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Zebra_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zebra.Zebra",
	HandlerType: (*ZebraServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InterfaceService",
			Handler:       _Zebra_InterfaceService_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RouterIdService",
			Handler:       _Zebra_RouterIdService_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RedistributeIPv4Service",
			Handler:       _Zebra_RedistributeIPv4Service_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RedistributeIPv6Service",
			Handler:       _Zebra_RedistributeIPv6Service_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RouteIPv4Service",
			Handler:       _Zebra_RouteIPv4Service_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RouteIPv6Service",
			Handler:       _Zebra_RouteIPv6Service_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "zebra.proto",
}

func init() { proto.RegisterFile("zebra.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 996 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0xc1, 0x6e, 0xf2, 0x46,
	0x10, 0x8e, 0x31, 0x60, 0x33, 0x10, 0xd8, 0x6c, 0x12, 0xe2, 0xf2, 0x57, 0x15, 0x45, 0xad, 0x84,
	0x52, 0x29, 0x6d, 0x68, 0x44, 0x2f, 0xbd, 0x10, 0x20, 0xbf, 0xac, 0x3f, 0x35, 0xd4, 0x10, 0xb5,
	0xea, 0x05, 0x19, 0xbc, 0x10, 0x4b, 0xc4, 0x76, 0x6d, 0x43, 0x93, 0xaa, 0xd7, 0xbe, 0x40, 0x9f,
	0xa7, 0x87, 0xaa, 0x6f, 0xd4, 0x37, 0xa8, 0x76, 0xbd, 0x86, 0x75, 0x08, 0xad, 0x9a, 0x43, 0x4f,
	0xff, 0x6d, 0x67, 0xe6, 0x9b, 0x6f, 0x66, 0x67, 0x76, 0xec, 0x81, 0xe2, 0xcf, 0x64, 0x1a, 0x58,
	0x17, 0x7e, 0xe0, 0x45, 0x1e, 0xce, 0x31, 0xa1, 0xd1, 0x03, 0xa4, 0xbb, 0x11, 0x09, 0xe6, 0xd6,
	0x8c, 0x98, 0xe4, 0xc7, 0x15, 0x09, 0x23, 0xfc, 0x01, 0x64, 0x3c, 0x5f, 0x93, 0xea, 0x52, 0xb3,
	0xdc, 0x2a, 0x5c, 0xc4, 0x4e, 0x03, 0xdf, 0xcc, 0x78, 0x3e, 0x3e, 0x85, 0xfc, 0x3a, 0x98, 0x4f,
	0x1c, 0x5b, 0xcb, 0xd4, 0xa5, 0xe6, 0xa1, 0x99, 0x5b, 0x07, 0x73, 0xdd, 0x6e, 0xfc, 0x25, 0x41,
	0x65, 0x43, 0x73, 0xe7, 0xdb, 0x56, 0x44, 0xfe, 0x3b, 0x0b, 0xc6, 0x90, 0x75, 0xad, 0x07, 0xa2,
	0xc9, 0x75, 0xa9, 0x59, 0x30, 0xd9, 0x19, 0x9f, 0x40, 0xce, 0x71, 0x6d, 0xf2, 0xa8, 0x65, 0x63,
	0x24, 0x13, 0x30, 0x02, 0xf9, 0x21, 0x5a, 0x69, 0x39, 0xa6, 0xa3, 0x47, 0x5c, 0x85, 0xfc, 0x03,
	0x89, 0x02, 0x67, 0xa6, 0xe5, 0x99, 0x92, 0x4b, 0xf8, 0x33, 0x28, 0x58, 0xb6, 0x1d, 0x4c, 0x1c,
	0x7f, 0x7d, 0xa5, 0x29, 0x75, 0xb9, 0x59, 0x6c, 0x95, 0x79, 0x32, 0x1d, 0xdb, 0x0e, 0x48, 0x18,
	0x9a, 0x2a, 0x05, 0xe8, 0xfe, 0xfa, 0x4a, 0x04, 0xb7, 0x35, 0xf5, 0x1f, 0xc1, 0xed, 0x46, 0x17,
	0x2a, 0xa6, 0xb7, 0x8a, 0x48, 0xa0, 0xdb, 0xaf, 0x2f, 0x5c, 0x0f, 0xca, 0x09, 0x09, 0x2f, 0xdb,
	0x16, 0x28, 0x89, 0xb5, 0x79, 0x03, 0x85, 0x80, 0x01, 0x13, 0x8a, 0x92, 0xa9, 0x06, 0xdc, 0xb3,
	0xf1, 0x0b, 0x9c, 0x99, 0xc4, 0x76, 0xc2, 0x28, 0x70, 0xa6, 0xab, 0x88, 0xe8, 0xc3, 0xf5, 0xd5,
	0xab, 0x53, 0xc2, 0x9f, 0x03, 0x30, 0xe2, 0x49, 0xf4, 0xe4, 0x13, 0x56, 0xf6, 0x72, 0x0b, 0x71,
	0x4f, 0x96, 0xeb, 0xf8, 0xc9, 0x27, 0x66, 0x9c, 0x0d, 0x3d, 0xbe, 0x10, 0xbd, 0xfd, 0x3f, 0x46,
	0xbf, 0x82, 0xfc, 0x30, 0x20, 0x73, 0xe7, 0x91, 0x3e, 0x1f, 0xda, 0x1c, 0x16, 0xae, 0x64, 0xb2,
	0x33, 0x7d, 0x16, 0x4b, 0xe2, 0x2e, 0xa2, 0x7b, 0x1e, 0x85, 0x4b, 0x8d, 0xaf, 0x40, 0x31, 0xc8,
	0x63, 0x74, 0xef, 0xf9, 0x2f, 0xba, 0x69, 0xa0, 0x38, 0xf3, 0xf8, 0xdd, 0xc5, 0x7e, 0x89, 0xd8,
	0xb8, 0x06, 0x85, 0x3f, 0x05, 0xfc, 0xb1, 0xe0, 0x58, 0x6c, 0x1d, 0xf2, 0x24, 0xe3, 0x64, 0x38,
	0xcf, 0x09, 0xe4, 0xe6, 0x4b, 0x6b, 0x11, 0x26, 0x77, 0x64, 0x42, 0xe3, 0xcf, 0x0c, 0x14, 0xd8,
	0x5d, 0x68, 0xa3, 0x5e, 0x51, 0xa3, 0x4f, 0x20, 0xcb, 0xaa, 0x23, 0xef, 0xa9, 0x0e, 0xb3, 0xe2,
	0x0b, 0x50, 0xc3, 0xd5, 0x54, 0xac, 0xe3, 0xb1, 0x88, 0x1c, 0xad, 0xa6, 0x0c, 0xac, 0x84, 0xf1,
	0x01, 0x7f, 0x0a, 0x79, 0x9f, 0xe5, 0xce, 0xc6, 0x6a, 0xe7, 0x42, 0xdc, 0x88, 0x6b, 0xa0, 0xd2,
	0x5e, 0x5b, 0xee, 0x8c, 0xf0, 0x51, 0xdb, 0xc8, 0xc2, 0x10, 0x2a, 0xa9, 0x21, 0x44, 0x20, 0x47,
	0xd6, 0x42, 0x53, 0xe3, 0x71, 0x8d, 0xac, 0x05, 0x2d, 0xcc, 0xcc, 0x5b, 0x7a, 0x81, 0x56, 0xa8,
	0xcb, 0xcd, 0x82, 0x19, 0x0b, 0xf8, 0x1c, 0x54, 0x37, 0xee, 0x4a, 0xa8, 0x41, 0x6a, 0xfc, 0x78,
	0xb3, 0xcc, 0x8d, 0x3d, 0x55, 0xc4, 0xf6, 0xfb, 0x22, 0xbe, 0xaa, 0x88, 0xe7, 0xbf, 0x4a, 0xbc,
	0x88, 0x2c, 0xf9, 0x0a, 0x14, 0x4d, 0xfd, 0x7a, 0x72, 0x67, 0xbc, 0x33, 0x06, 0xdf, 0x19, 0xe8,
	0x00, 0x97, 0x01, 0xa8, 0xe2, 0x5d, 0xdf, 0x34, 0xfa, 0xb7, 0x48, 0xc2, 0x47, 0x70, 0x48, 0xe5,
	0xee, 0xc0, 0x30, 0xfa, 0xdd, 0x71, 0xbf, 0x87, 0x32, 0x09, 0x64, 0x34, 0xee, 0x8c, 0xf5, 0x2e,
	0x92, 0x71, 0x11, 0x14, 0x2a, 0x9b, 0xfa, 0x10, 0x65, 0x71, 0x09, 0x54, 0x2a, 0x0c, 0x46, 0xc3,
	0x1b, 0x94, 0x4b, 0x24, 0x7d, 0xa4, 0x8f, 0x50, 0x3e, 0x01, 0x5e, 0xbf, 0x1d, 0x22, 0xe5, 0xfc,
	0xb7, 0x0c, 0x94, 0xc4, 0x82, 0xe2, 0x63, 0xa8, 0x30, 0xda, 0xbb, 0xd8, 0x7b, 0xa2, 0x77, 0xd0,
	0x01, 0x3e, 0x83, 0xe3, 0x94, 0xd2, 0x18, 0x8d, 0x3a, 0x93, 0x4b, 0x24, 0xbd, 0x6c, 0x68, 0xa1,
	0x0c, 0x7e, 0x03, 0x67, 0x29, 0x43, 0xff, 0xfb, 0x71, 0xdf, 0x34, 0x3a, 0xb7, 0x93, 0x4b, 0x24,
	0xef, 0x37, 0xb6, 0x50, 0x16, 0x9f, 0x00, 0x4a, 0x8c, 0xd7, 0x6f, 0x87, 0x13, 0x9d, 0xe6, 0x99,
	0x7b, 0xae, 0xed, 0x53, 0x6d, 0x1e, 0x57, 0x01, 0x8b, 0xda, 0xee, 0xc0, 0xb8, 0xe9, 0xf7, 0x90,
	0x22, 0x5e, 0x82, 0x5e, 0x7a, 0x72, 0x7b, 0x89, 0xd4, 0x5d, 0x65, 0x0b, 0x15, 0x76, 0x94, 0x7a,
	0x07, 0xc1, 0xf9, 0x1f, 0x32, 0x64, 0x06, 0x3e, 0xed, 0x8a, 0xe1, 0x0d, 0x7c, 0x12, 0x58, 0x91,
	0xe3, 0xb9, 0xe8, 0x80, 0x86, 0xdb, 0xfc, 0x6b, 0x47, 0xab, 0x69, 0x38, 0x0b, 0x9c, 0x29, 0x41,
	0x12, 0xd6, 0xe0, 0x64, 0xfb, 0x0f, 0x76, 0xc3, 0x8d, 0x25, 0x83, 0x4f, 0xe1, 0x28, 0xf9, 0xcb,
	0x6c, 0x1d, 0x64, 0x56, 0xb6, 0xe4, 0xe7, 0x23, 0xe0, 0xb3, 0x2c, 0x1d, 0xf6, 0x45, 0xdf, 0xa2,
	0x73, 0x8c, 0x84, 0x29, 0x45, 0x6c, 0x1e, 0xd7, 0xa0, 0x1a, 0xab, 0x7b, 0x64, 0x6e, 0xad, 0x96,
	0x82, 0x8b, 0x82, 0x3f, 0x04, 0x2d, 0x65, 0x13, 0x3d, 0x55, 0xf6, 0x1e, 0x68, 0xf8, 0x8e, 0x6d,
	0xa3, 0x02, 0x7b, 0x7c, 0x54, 0xea, 0x91, 0x25, 0x89, 0x08, 0x02, 0x8c, 0xa0, 0xb4, 0xb9, 0x0e,
	0x85, 0x14, 0x69, 0x5a, 0x1b, 0x0d, 0x87, 0x95, 0x68, 0x4b, 0x44, 0x58, 0x40, 0xa1, 0x87, 0xf4,
	0x6a, 0x29, 0x2d, 0x87, 0x97, 0x69, 0x18, 0x61, 0x51, 0x41, 0x15, 0xfa, 0xa6, 0xb7, 0xa4, 0xde,
	0x4f, 0x2e, 0x42, 0x29, 0xe7, 0x9b, 0xa5, 0xb5, 0xe8, 0xde, 0x5b, 0xee, 0x82, 0xa0, 0xa3, 0x94,
	0xc1, 0xb0, 0x1e, 0x08, 0x37, 0xe0, 0x54, 0x4b, 0xbe, 0x89, 0x56, 0x5c, 0x7f, 0xdc, 0xfa, 0x5d,
	0x86, 0xdc, 0x0f, 0x74, 0xf6, 0xb0, 0x2e, 0xa4, 0x39, 0x22, 0xc1, 0xda, 0x99, 0x11, 0x7c, 0xc6,
	0xe7, 0xf2, 0xf9, 0x02, 0x56, 0xab, 0x3e, 0x37, 0xc4, 0xbb, 0x41, 0xe3, 0xa0, 0x29, 0x7d, 0x21,
	0xe1, 0x9b, 0xed, 0xe2, 0x91, 0x30, 0x55, 0xc5, 0x8f, 0xd2, 0x76, 0x21, 0xa9, 0x9d, 0x3e, 0xd3,
	0xa7, 0x78, 0xbe, 0xdd, 0xdd, 0x1a, 0x12, 0xbe, 0x8f, 0x12, 0xbf, 0x97, 0xb7, 0x8a, 0x5a, 0xea,
	0x73, 0x49, 0x0d, 0x7b, 0x29, 0xdb, 0xff, 0x42, 0xd9, 0xde, 0x47, 0xd9, 0xe6, 0x94, 0x5f, 0x03,
	0xda, 0x44, 0x49, 0xb8, 0x76, 0xc2, 0xef, 0x4d, 0x48, 0xf0, 0x6e, 0xef, 0xf3, 0x6e, 0xef, 0x8b,
	0x3d, 0xcd, 0xb3, 0x55, 0xf9, 0xcb, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x19, 0xb7, 0x75,
	0x39, 0x0b, 0x00, 0x00,
}
